const canvas=document.getElementById('chart'),ctx=canvas.getContext('2d');
const launchBtn=document.getElementById('launchBtn'),pauseBtn=document.getElementById('pauseBtn'),aiPanel=document.getElementById('aiPanel'),aiTitle=document.getElementById('aiTitle'),aiMessage=document.getElementById('aiMessage'),activity=document.getElementById('activity'),activityText=document.getElementById('activityText'),runtime=document.getElementById('runtime'),quotePrice=document.getElementById('quotePrice'),priceTag=document.getElementById('priceTag'),symbolLabel=document.getElementById('symbolLabel'),profitResult=document.getElementById('profitResult'),profitAmount=document.getElementById('profitAmount');
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let candles=[],base=67248.32,running=false,paused=false,lastFrame=0,elapsed=0,stateTimer=0,raf,runtimeStart=0,timerId;
const symbols={'BTC/USD':['Bitcoin / U.S. Dollar',67248.32],'ETH/USD':['Ethereum / U.S. Dollar',3541.18],'S&P 500':['S&P 500 Index',5764.03]};
let accountBalance=350;
const portfolioValue=document.getElementById('portfolioValue');
function sessionProfit(){const pct=.005+Math.random()*.005;return(accountBalance*pct).toFixed(2)}
function sessionProfitPercent(profit){return((Number(profit)/accountBalance)*100).toFixed(2)}
function updatePortfolioValue(){const parts=accountBalance.toFixed(2).split('.');portfolioValue.innerHTML='$'+Number(parts[0]).toLocaleString('en-US')+'<span>.'+parts[1]+'</span>'}
function seed(){candles=[];let p=base*.975;for(let i=0;i<58;i++){const open=p,close=open+(Math.random()-.46)*base*.0035,high=Math.max(open,close)+Math.random()*base*.0018,low=Math.min(open,close)-Math.random()*base*.0018;candles.push({open,close,high,low});p=close}}
function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);draw()}
function draw(){const w=canvas.clientWidth,h=canvas.clientHeight,pad={t:25,r:63,b:28,l:10};ctx.clearRect(0,0,w,h);const vals=candles.flatMap(c=>[c.high,c.low]),min=Math.min(...vals),max=Math.max(...vals),range=max-min||1,y=v=>pad.t+(max-v)/range*(h-pad.t-pad.b);ctx.strokeStyle='#e6ece7';ctx.lineWidth=1;ctx.font='10px DM Sans';ctx.fillStyle='#91a09b';for(let i=0;i<5;i++){let yy=pad.t+i*(h-pad.t-pad.b)/4;ctx.beginPath();ctx.moveTo(pad.l,yy);ctx.lineTo(w-pad.r,yy);ctx.stroke();ctx.fillText(formatNumber(max-i*range/4),w-pad.r+8,yy+3)}const visible=52,gap=(w-pad.l-pad.r)/visible,bw=Math.max(4,Math.min(9,gap*.58)),start=Math.max(0,candles.length-visible);candles.slice(start).forEach((c,i)=>{let x=pad.l+i*gap+gap/2,col=c.close>=c.open?'#239476':'#d86661';ctx.strokeStyle=col;ctx.beginPath();ctx.moveTo(x,y(c.high));ctx.lineTo(x,y(c.low));ctx.stroke();ctx.fillStyle=col;const top=y(Math.max(c.open,c.close)),bot=y(Math.min(c.open,c.close));ctx.fillRect(x-bw/2,top,bw,Math.max(2,bot-top))});const last=candles.at(-1);if(last){const py=y(last.close);ctx.setLineDash([4,4]);ctx.strokeStyle='#2394766b';ctx.beginPath();ctx.moveTo(pad.l,py);ctx.lineTo(w-pad.r,py);ctx.stroke();ctx.setLineDash([]);priceTag.style.top=Math.max(22,Math.min(h-24,py-9))+'px'}}
function formatNumber(v){return v>=10000?v.toLocaleString('en-US',{maximumFractionDigits:0}):v.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}
function updateQuote(){const v=candles.at(-1)?.close||base;quotePrice.textContent='$'+v.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});priceTag.textContent=formatNumber(v)}
const states=[['AI analyzing…','Scanning simulated momentum and market structure.'],['Opportunity detected','A potential pattern was found in this simulation.'],['Trade opened','A simulated position was opened — no real funds involved.']];let stateIndex=0;
function cycleState(){stateIndex=(stateIndex+1)%states.length;activityText.textContent=states[stateIndex][0];aiMessage.textContent=states[stateIndex][1]}
function animate(t){if(!running)return;if(!paused){const dt=Math.min(50,t-lastFrame||16);elapsed+=dt;stateTimer+=dt;const c=candles.at(-1),volatility=base*.00015;c.close+=((Math.random()-.485)*volatility)*(dt/16);c.high=Math.max(c.high,c.close);c.low=Math.min(c.low,c.close);if(elapsed>1050){elapsed=0;const next=c.close;candles.push({open:next,close:next,high:next,low:next});if(candles.length>65)candles.shift()}if(stateTimer>3800){stateTimer=0;cycleState()}if(Date.now()-runtimeStart>=15000){completeSession();return}updateQuote();draw()}lastFrame=t;raf=requestAnimationFrame(animate)}
function start(){running=true;paused=false;lastFrame=performance.now();stateTimer=0;stateIndex=0;profitResult.hidden=true;aiPanel.classList.remove('completed');aiPanel.classList.add('active');aiTitle.textContent='AI Trading Active';aiMessage.textContent=states[0][1];activityText.textContent=states[0][0];activity.hidden=false;pauseBtn.hidden=false;pauseBtn.textContent='Ⅱ';pauseBtn.setAttribute('aria-label','Pause simulation');launchBtn.classList.add('stop');launchBtn.innerHTML='<span>■</span> Stop AI';runtimeStart=Date.now();if(!reduced)raf=requestAnimationFrame(animate);else{draw();setTimeout(()=>running&&completeSession(),15000)}timerId=setInterval(updateRuntime,1000)}
function stop(){running=false;paused=false;cancelAnimationFrame(raf);clearInterval(timerId);aiPanel.classList.remove('active','completed');aiTitle.textContent='AI Trading System is ready';aiMessage.textContent='Launch a simulated session to watch the market unfold.';activity.hidden=true;profitResult.hidden=true;pauseBtn.hidden=true;launchBtn.classList.remove('stop');launchBtn.innerHTML='<span>✦</span> Launch AI'}
function completeSession(){if(!running)return;running=false;paused=false;cancelAnimationFrame(raf);clearInterval(timerId);const profit=sessionProfit(),pct=sessionProfitPercent(profit);accountBalance+=Number(profit);updatePortfolioValue();aiPanel.classList.remove('active');aiPanel.classList.add('completed');aiTitle.textContent='Potential Profit claimed Successfully. Get started before all spots are filled.';aiMessage.textContent='The demo session completed successfully. Ready to launch again.';activityText.textContent='Session complete';pauseBtn.hidden=true;launchBtn.classList.remove('stop');launchBtn.innerHTML='<span>↻</span> Launch AI again';profitAmount.textContent='+$'+profit;profitResult.hidden=false;toast.textContent='Ka-ching! +$'+profit+' ('+pct+'%) simulated profit';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),4200)}
launchBtn.addEventListener('click',()=>running?stop():start());pauseBtn.addEventListener('click',()=>{paused=!paused;pauseBtn.textContent=paused?'▶':'Ⅱ';pauseBtn.setAttribute('aria-label',paused?'Resume simulation':'Pause simulation');aiTitle.textContent=paused?'Simulation paused':'AI Trading Active';if(!paused)lastFrame=performance.now()});
function updateRuntime(){let s=Math.floor((Date.now()-runtimeStart)/1000),m=Math.floor(s/60);runtime.textContent=String(m).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
document.querySelectorAll('[data-symbol]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-symbol]').forEach(x=>x.setAttribute('aria-selected','false'));b.setAttribute('aria-selected','true');const s=symbols[b.dataset.symbol];base=s[1];symbolLabel.textContent=s[0];canvas.setAttribute('aria-label','Animated simulated '+b.dataset.symbol+' Japanese candlestick chart');seed();updateQuote();draw()}));
document.querySelectorAll('.time-switcher button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.time-switcher button').forEach(x=>x.classList.remove('active'));b.classList.add('active');seed();draw()}));
const dialog=document.getElementById('demoDialog'),dialogTitle=document.getElementById('dialogTitle'),dialogDescription=document.getElementById('dialogDescription'),dialogIcon=document.getElementById('dialogIcon'),dialogSubmit=document.getElementById('dialogSubmit'),depositPanel=document.getElementById('dialogDepositPanel'),withdrawPanel=document.getElementById('dialogWithdrawPanel'),toast=document.getElementById('toast');
function openWithdrawDialog(){dialog.dataset.type='withdraw-blocked';dialogTitle.textContent='Withdrawal';dialogDescription.textContent='Your account is inactive. To make withdrawals, activate your account with an initial deposit first.';dialogIcon.textContent='↗';dialogIcon.classList.add('dialog-icon-muted');depositPanel.hidden=true;withdrawPanel.hidden=false;dialogSubmit.textContent='Make deposit';dialogSubmit.value='deposit-cta';dialog.showModal()}
const agentParam=(new URLSearchParams(location.search).get('agent')||new URLSearchParams(location.search).get('ref')||'').replace(/[^a-zA-Z0-9_-]/g,'').slice(0,40);
if(agentParam){sessionStorage.setItem('demoAgentRef',agentParam);document.getElementById('agentCode').textContent=agentParam;document.getElementById('agentReference').hidden=false}
document.querySelectorAll('[data-action="withdraw"]').forEach(b=>b.addEventListener('click',openWithdrawDialog));
dialog.addEventListener('close',()=>{if(dialog.returnValue==='deposit-cta'){window.location.href=window.depositPageUrl()}});
addEventListener('resize',resize);seed();resize();
